#pragma once

#define CONFIG_TIME_SLICE (CLOCKS_PER_SEC / 100)
#define CONFIG_TIMER_HZ 1024
#define CONFIG_KERNEL_STACK (PAGE_SIZE)
#define CONFIG_USER_STACK (PAGE_SIZE)
#define CONFIG_MAX_FD 64
#define CONFIG_MAX_ARG 256
#define CONFIG_LOG_SERIAL true
