#pragma once

#define CONFIG_TIME_SLICE (SEC / 500)
#define CONFIG_SCHED_HZ 1024
#define CONFIG_KERNEL_STACK (PAGE_SIZE)
#define CONFIG_USER_STACK (PAGE_SIZE)
#define CONFIG_MAX_NAME 32
#define CONFIG_MAX_LABEL 32
#define CONFIG_MAX_FILE 64
#define CONFIG_DWM_FPS 100
#define CONFIG_LOG_SERIAL true
