IMAGE = bin/PatchworkOS.img

export ROOT_DIR := $(abspath .)
export BUILD_DIR := $(ROOT_DIR)/build
export BIN_DIR := $(ROOT_DIR)/bin
export COMP_DIR := $(ROOT_DIR)/comp
export VENDOR_DIR := $(ROOT_DIR)/vendor
export STAGING_DIR := $(BUILD_DIR)/staging
export INITRD_DIR := $(BUILD_DIR)/initrd
export LIBSTD_DIR := $(COMP_DIR)/core/libc
export KERNEL_HEADERS_DIR := $(COMP_DIR)/core/kernel-headers
export CMAKE_TOOLCHAIN_FILE := $(ROOT_DIR)/tools/patchworkos-toolchain.cmake

VERSION_STRING := $(shell git describe --tags --always --dirty --long 2>/dev/null || echo "unknown")
VERSION_HEADER = $(KERNEL_HEADERS_DIR)/include/kernel/version.h

INITRD_DIR = $(BIN_DIR)/initrd
INITRD_TAR = $(BIN_DIR)/initrd.tar

COMP_MKS := $(shell find comp/ -name "*.mk" 2>/dev/null)
COMP_NAMES := $(basename $(notdir $(COMP_MKS)))
COMP_TARGETS := $(patsubst %,$(BIN_DIR)/.%.built,$(COMP_NAMES))

.PHONY: all clean image deploy staging

all: staging $(IMAGE)

$(VERSION_HEADER):
	@printf "#pragma once\n\n" > $@.tmp
	@printf "/**\n * @file version.h\n * @brief Generated by Makefile from Git information.\n */\n\n" >> $@.tmp
	@printf "#define OS_NAME \"PatchworkOS\"\n" >> $@.tmp
	@printf "#define OS_VERSION \"$(VERSION_STRING)\"\n\n" >> $@.tmp
	@if ! cmp -s $@ $@.tmp 2>/dev/null; then \
		mv $@.tmp $@; \
		echo "GEN     $(VERSION_HEADER)"; \
	else \
		rm $@.tmp; \
	fi

$(VENDOR_DIR)/gnu-efi/.built:
	@if [ ! -d "$(VENDOR_DIR)/gnu-efi" ]; then \
		echo "CLONE   gnu-efi"; \
		git clone https://github.com/ncroxon/gnu-efi.git $(VENDOR_DIR)/gnu-efi >/dev/null 2>&1; \
	fi
	@echo "BUILD   gnu-efi"
	@$(MAKE) -C $(VENDOR_DIR)/gnu-efi CC="clang --config $(ROOT_DIR)/tools/patchworkos.cfg" AR="llvm-ar" LD="ld.lld" OBJCOPY="llvm-objcopy" >/dev/null 2>&1
	@touch $@

staging: $(VENDOR_DIR)/gnu-efi/.built $(VERSION_HEADER)
	@echo "STAGING headers"
	@rm -rf $(STAGING_DIR)/include
	@mkdir -p $(STAGING_DIR)/include
	@cp -r $(VENDOR_DIR)/gnu-efi/inc $(STAGING_DIR)/include/gnu-efi/ 2>/dev/null || true
	@cp -r $(ROOT_DIR)/boot/include $(STAGING_DIR)/include/boot/ 2>/dev/null || true
	@for mk in $(COMP_MKS); do \
		COMP_DIR=$$(dirname $$mk); \
		if [ -d "$$COMP_DIR/include" ]; then \
			cp -r $$COMP_DIR/include/* $(STAGING_DIR)/include/ 2>/dev/null || true; \
		fi; \
	done
	
$(BIN_DIR)/.boot.built: $(shell find $(ROOT_DIR)/boot/src $(ROOT_DIR)/boot/include -type f 2>/dev/null)
	@echo "BUILD   boot"
	@$(MAKE) -s --no-print-directory -f boot/boot.mk
	@touch $@

$(BIN_DIR)/.init.built: $(BIN_DIR)/.libc.built $(shell find $(ROOT_DIR)/init -type f 2>/dev/null)
	@echo "BUILD   init"
	@$(MAKE) -s --no-print-directory -f init/init.mk
	@touch $@

$(BIN_DIR)/.kernel.built: $(shell find $(ROOT_DIR)/kernel -type f 2>/dev/null)
	@echo "BUILD   kernel"
	@$(MAKE) -s --no-print-directory -f kernel/kernel.mk
	@touch $@

define COMP_RULE
COMP_DEPS_$(1) := $$(strip $$(shell grep -E '^[[:space:]]*COMP_DEPENDS[[:space:]]*(\+|:)?=' $$(filter %/$(1).mk,$$(COMP_MKS)) | cut -d '=' -f 2))
COMP_DIR_$(1) := $$(patsubst %/,%,$$(dir $$(filter %/$(1).mk,$$(COMP_MKS))))

$(BIN_DIR)/.$(1).built: $$(patsubst %,$(BIN_DIR)/.%.built,$$(COMP_DEPS_$(1))) $$(shell find $$(COMP_DIR_$(1)) -type f 2>/dev/null)
	@echo "BUILD   component $(1)"
	@$$(MAKE) -s --no-print-directory -f $$(filter %/$(1).mk,$$(COMP_MKS)) \
		SRC_DIR=$$(patsubst %/,%/src,$$(dir $$(filter %/$(1).mk,$$(COMP_MKS)))) \
		MY_DIR=$$(patsubst %/,%,$$(dir $$(filter %/$(1).mk,$$(COMP_MKS)))) \
		all
	@touch $$@
endef
$(foreach comp,$(COMP_NAMES),$(eval $(call COMP_RULE,$(comp))))

$(BIN_DIR)/initrd.tar: $(BIN_DIR)/.kernel.built $(BIN_DIR)/.init.built $(BIN_DIR)/.boot.built $(COMP_TARGETS)
	@echo "PACK    initrd.tar"
	@tar -cf $@ -C $(INITRD_DIR) .

$(IMAGE): $(BIN_DIR)/initrd.tar
	@echo "DEPLOY  $(IMAGE)"
	@mkdir -p $(BIN_DIR)
	@dd if=/dev/zero of=$(IMAGE) bs=2M count=64 2>/dev/null
	@mformat -F -C -t 256 -h 16 -s 63 -v "PATCHWORK" -i $(IMAGE) ::
	@mmd -i $(IMAGE) ::/efi ::/efi/boot ::/boot
	@mcopy -i $(IMAGE) -s $(VENDOR_DIR)/startup.nsh ::/ 2>/dev/null || true
	@mcopy -i $(IMAGE) -s $(BIN_DIR)/boot/bootx64.efi ::/efi/boot/ 2>/dev/null || true
	@mcopy -i $(IMAGE) -s $(BIN_DIR)/kernel/kernel ::/boot/ 2>/dev/null || true
	@mcopy -i $(IMAGE) -s $(BIN_DIR)/init/init ::/boot/ 2>/dev/null || true
	@mcopy -i $(IMAGE) -s $(ROOT_DIR)/init/init.scon ::/boot/ 2>/dev/null || true
	@mcopy -i $(IMAGE) -s $(BIN_DIR)/initrd.tar ::/boot/ 2>/dev/null || true

clean:
	@echo "CLEAN   all"
	@rm -rf $(BUILD_DIR) $(BIN_DIR)

grub_loopback: $(IMAGE)
	@echo "COPY    $(IMAGE) to /data"
	@cp $(IMAGE) /data/PatchworkOS.img

compile_commands: clean
	@echo "GEN     compile_commands.json"
	@bear -- $(MAKE) all

format:
	@echo "FORMAT  source code"
	@find comp/ boot/ kernel/ init/ meta/doxy tools/ -iname '*.h' -o -iname '*.c' -o -iname '*.dox' 2>/dev/null | xargs clang-format -style=file -i

doxygen:
	@if [ ! -d "meta/docs/doxygen-awesome-css" ]; then \
		echo "CLONE   doxygen-awesome-css"; \
		git clone https://github.com/jothepro/doxygen-awesome-css.git meta/docs/doxygen-awesome-css >/dev/null 2>&1; \
		cd meta/docs/doxygen-awesome-css && git checkout v2.3.4 >/dev/null 2>&1; \
	fi
	@echo "GEN     documentation"
	@GIT_VERSION_STRING=$$(git describe --tags --always --dirty --long 2>/dev/null || echo "unknown"); \
	sed -i "s/^PROJECT_NUMBER.*/PROJECT_NUMBER = \"$$GIT_VERSION_STRING\"/" meta/doxy/Doxyfile
	@doxygen meta/doxy/Doxyfile
	@mkdir -p meta/docs/html/meta/screenshots
	@cp meta/screenshots/* meta/docs/html/meta/screenshots/ 2>/dev/null || true

QEMU_MEMORY ?= 2G
QEMU_CPUS ?= $(shell nproc 2>/dev/null || echo 8)
QEMU_MACHINE ?= q35
QEMU_ARGS ?=

QEMU_FLAGS = \
	-M $(QEMU_MACHINE) \
	-drive format=raw,file=$(IMAGE) \
	-m $(QEMU_MEMORY) \
	-smp $(QEMU_CPUS) \
	-cpu qemu64 \
	-drive if=pflash,format=raw,unit=0,file=$(VENDOR_DIR)/OVMFbin/OVMF_CODE-pure-efi.fd,readonly=on \
	-drive if=pflash,format=raw,unit=1,file=$(VENDOR_DIR)/OVMFbin/OVMF_VARS-pure-efi.fd

ifeq ($(QEMU_NOGRAPHIC),1)
QEMU_FLAGS += -nographic
else
QEMU_FLAGS += -display sdl -serial stdio
endif

ifeq ($(DEBUG),1)
else
QEMU_FLAGS += -no-shutdown -no-reboot
endif

ifeq ($(QEMU_EXIT_ON_PANIC),1)
QEMU_FLAGS += -device isa-debug-exit
endif

ifeq ($(GDB),1)
QEMU_FLAGS += -s -S
endif

run: $(IMAGE)
	@echo "RUN     qemu"
	@qemu-system-x86_64 $(QEMU_FLAGS) $(QEMU_ARGS)

lib/acpica_tests/.built: | lib
	@if [ ! -d "lib/acpica" ]; then \
		echo "CLONE   acpica"; \
		git clone https://github.com/KaiNorberg/acpica.git -b fix_runtime_implicit_return_test lib/acpica >/dev/null 2>&1; \
	fi
	@if [ ! -d "lib/acpica_tests" ]; then \
		echo "BUILD   acpica_tests"; \
		mkdir -p lib/acpica_tests; \
		cd lib/acpica && \
		sed -i '/Method (CH04, 7, NotSerialized)/{N;s/Method (CH04, 7, NotSerialized)\n    {/&\n        Return (0x00) \/* Disabled *\//;}' tests/aslts/src/runtime/cntl/ehandle.asl 2>/dev/null || true && \
		COLLECTIONS="functional"; \
		for COLLECTION in $$COLLECTIONS; do \
			ALL_FILES=$$(find tests/aslts/src/runtime/collections/$$COLLECTION -type f -name 'MAIN.asl' ! -path '*FULL*' 2>/dev/null); \
			for FILE in $$ALL_FILES; do \
				DIR=$$(dirname $$FILE); \
				OUT_DIR=../acpica_tests/$${DIR#tests/aslts/src/runtime/collections/}; \
				mkdir -p $$OUT_DIR; \
				iasl -va -oa -f -p $$OUT_DIR/test.aml $$FILE >/dev/null 2>&1 || true; \
				xxd -i $$OUT_DIR/test.aml 2>/dev/null | sed 's/^unsigned/static unsigned/' > $$OUT_DIR/test.h 2>/dev/null || true; \
			done; \
		done; \
	fi
	@if [ ! -f "lib/acpica_tests/all_tests.h" ]; then \
		cd lib/acpica_tests && \
		echo "#pragma once" > all_tests.h && \
		echo "" >> all_tests.h && \
		echo "/**" >> all_tests.h && \
		echo " * @file all_tests.h" >> all_tests.h && \
		echo " * @brief Generated by Makefile from ACPICA test suite." >> all_tests.h && \
		echo " */" >> all_tests.h && \
		echo "" >> all_tests.h && \
		find . -type f -name 'test.h' 2>/dev/null | while read line; do \
			echo "#include \"$${line#lib/}\"" >> all_tests.h; \
		done && \
		echo "" >> all_tests.h && \
		echo "#define ACPICA_TEST_COUNT $$(find . -type f -name 'test.h' 2>/dev/null | wc -l)" >> all_tests.h && \
		echo "" >> all_tests.h && \
		echo "typedef struct" >> all_tests.h && \
		echo "{" >> all_tests.h && \
		echo "    const char* name;" >> all_tests.h && \
		echo "    unsigned int length;" >> all_tests.h && \
		echo "    unsigned char* aml;" >> all_tests.h && \
		echo "} acpica_test_t;" >> all_tests.h && \
		echo "" >> all_tests.h && \
		echo "static acpica_test_t acpicaTests[ACPICA_TEST_COUNT] = {" >> all_tests.h && \
		find . -type f -name 'test.aml' 2>/dev/null | while read line; do \
			XXD_NAME=___acpica_tests_$$(echo $${line#./} | tr '/' '_' | tr '-' '_' | tr '.' '_'); \
			echo "    { \"$${line#./}\", sizeof($${XXD_NAME}), $${XXD_NAME} }," >> all_tests.h; \
		done && \
		echo "};" >> all_tests.h; \
	fi
	@touch $@
