#ifndef _SYS_FS_H
#define _SYS_FS_H 1

#if defined(__cplusplus)
extern "C"
{
#endif

#include <alloca.h>
#include <libc/status.h>
#include <libc/syscall.h>
#include <sys/stat.h>

#include "_libc/MAX_NAME.h"
#include "_libc/MAX_PATH.h"
#include "_libc/NULL.h"
#include "_libc/clock_t.h"
#include "_libc/config.h"
#include "_libc/offsetof.h"
#include "_libc/size_t.h"
#include "_libc/ssize_t.h"
#include "_libc/time_t.h"
#include "_libc/uint16_t.h"
#include "_libc/uint8_t.h"

/**
 * @brief Filesystem interface.
 * @defgroup libc_fs Filesystem
 * @ingroup libc
 *
 * @{
 */

#define FDKEY_MAX 128 ///< Maximum size of a key generated by `fdshare()`.
#define FDKEY_128 25  ///< The size of a buffer needed to hold a 128-bit key.
#define FDKEY_256 45  ///< The size of a buffer needed to hold a 256-bit key.
#define FDKEY_512 89  ///< The size of a buffer needed to hold a 512-bit key.

typedef uint64_t fd_t;      ///< File descriptor type.
#define FDIN ((fd_t)0)      ///< Standard input file descriptor.
#define FDOUT ((fd_t)1)     ///< Standard output file descriptor.
#define FDERR ((fd_t)2)     ///< Standard error file descriptor.
#define FDCWD ((fd_t)3)     ///< Standard current working directory file descriptor.
#define FDROOT ((fd_t)4)    ///< Standard root file descriptor.
#define FDNONE ((fd_t) - 1) ///< No file descriptor.

/**
 * @brief System call for duplicating file descriptors.
 *
 * @param oldFd The open file descriptor to duplicate.
 * @param newFd Output pointer for the new file descriptor, if `FDNONE` any free file descriptor will be used,
 * otherwise the specified file descriptor will be used.
 * @return An appropriate status value.
 */
static inline status_t fddup(fd_t oldFd, fd_t* newFd)
{
    return syscall2(SYS_FD_DUP, newFd, oldFd, *newFd);
}

/**
 * @brief System call for binding a source path to a target path.
 *
 * @param root The file descriptor containing the binding table to add the bind to.
 * @param target The file descriptor to the target location where the source will appear.
 * @param source The file descriptor to the source location.
 * @return An appropriate status value.
 */
static inline status_t fdbind(fd_t root, fd_t target, fd_t source)
{
    return syscall3(SYS_FD_BIND, NULL, root, target, source);
}

/**
 * @brief System call for unbinding a path.
 *
 * @param root The file descriptor containing the binding table to remove the bind from.
 * @param target The file descriptor to the target location to unbind.
 * @return An appropriate status value.
 */
static inline status_t fdunbind(fd_t root, fd_t target)
{
    return syscall2(SYS_FD_UNBIND, NULL, root, target);
}

typedef uint64_t file_volume_t; ///< File volume id type, uniquely identifies a filesystem volume.

typedef uint64_t file_number_t; ///< File number type, uniquely identifies a file within its volume.

typedef uint64_t file_type_t; ///< File type enum.
#define FILE_TYPE_UNKNOWN 0   ///< Unknown file type.
#define FILE_TYPE_REGULAR 1   ///< Regular file.
#define FILE_TYPE_DIRECTORY 3 ///< Directory.
#define FILE_TYPE_SYMLINK 4   ///< Symbolic link.
#define FILE_TYPE_DEVICE 5    ///< Device file.
#define FILE_TYPE_SYSTEM 6    ///< System file, used for exposing kernel information to user space.

typedef uint16_t file_attr_t; ///< File attribute operations.
#define _FILE_GET(x) (((x) << 1) & ~1)
#define _FILE_SET(x) (((x) << 1) | 1)
#define FILE_GET_SIZE _FILE_GET(0)       ///< Get the size of the file.
#define FILE_SET_SIZE _FILE_SET(0)       ///< Set the size of the file.
#define FILE_GET_BLOCKS _FILE_GET(1)     ///< Get the number of blocks allocated.
#define FILE_GET_BLOCK_SIZE _FILE_GET(2) ///< Get the block size.
#define FILE_GET_MAX_SIZE _FILE_GET(3)   ///< Get the maximum file size.
#define FILE_GET_ATIME _FILE_GET(4)      ///< Get the access time.
#define FILE_SET_ATIME _FILE_SET(4)      ///< Set the access time.
#define FILE_GET_MTIME _FILE_GET(5)      ///< Get the modification time.
#define FILE_SET_MTIME _FILE_SET(5)      ///< Set the modification time.
#define FILE_GET_CTIME _FILE_GET(6)      ///< Get the change time.
#define FILE_SET_CTIME _FILE_SET(6)      ///< Set the change time.
#define FILE_GET_BTIME _FILE_GET(7)      ///< Get the birth time.
#define FILE_SET_BTIME _FILE_SET(7)      ///< Set the birth time.
#define FILE_GET_NLINK _FILE_GET(8)      ///< Get the number of hard links.
#define FILE_GET_NUMBER _FILE_GET(9)     ///< Get the file number.
#define FILE_GET_VOLUME _FILE_GET(10)    ///< Get the volume ID.
#define FILE_GET_TYPE _FILE_GET(11)      ///< Get the file type.

#define FILE_ATTR_IS_SET(attr) ((attr) & 1)
#define FILE_ATTR_IS_GET(attr) (!((attr) & 1))

typedef uint64_t file_mask_t;         ///< Bitmask of which fields are valid within a `file_info_t` structure.
#define FILE_MASK_SIZE (1 << 0)       ///< File size is valid.
#define FILE_MASK_BLOCKS (1 << 1)     ///< Blocks allocated is valid.
#define FILE_MASK_BLOCK_SIZE (1 << 2) ///< Block size is valid.
#define FILE_MASK_MAX_SIZE (1 << 3)   ///< Maximum file size is valid.
#define FILE_MASK_ATIME (1 << 4)      ///< Access time is valid.
#define FILE_MASK_MTIME (1 << 5)      ///< Modification time is valid.
#define FILE_MASK_CTIME (1 << 6)      ///< Change time is valid.
#define FILE_MASK_BTIME (1 << 7)      ///< Birth/Creation time is valid.
#define FILE_MASK_NLINK (1 << 8)      ///< Number of hard links is valid.
#define FILE_MASK_NUMBER (1 << 9)     ///< File number is valid.
#define FILE_MASK_VOLUME (1 << 10)    ///< Volume ID is valid.
#define FILE_MASK_TYPE (1 << 11)      ///< File type is valid.
#define FILE_MASK_NAME (1 << 12)      ///< File name is valid.
#define FILE_MASK_MODE (1 << 13)      ///< File mode is valid.

/**
 * @brief File information structure.
 * @struct file_info_t
 */
typedef struct file_info
{
    file_mask_t mask;     ///< Bitmask of which fields are valid.
    size_t size;          ///< File size in bytes.
    size_t blocks;        ///< Blocks allocated.
    size_t blockSize;     ///< Block size in bytes.
    size_t maxSize;       ///< Maximum file size.
    time_t atime;         ///< Access time.
    time_t mtime;         ///< Modification time.
    time_t ctime;         ///< Change time.
    time_t btime;         ///< Birth/Creation time.
    uint32_t nlink;       ///< Number of hard links.
    file_number_t number; ///< File number.
    file_volume_t volume; ///< Volume ID.
    file_type_t type;     ///< File type.
    char name[MAX_NAME];  ///< File name.
    char mode[MAX_NAME];  ///< File mode represented by their short-hand.
} file_info_t;

/**
 * @brief Path flags and permissions.
 * @enum path_mode_t
 *
 * We store both flags and permissions in the same enum but permissions are sometimes treated differently to flags.
 */
typedef enum path_mode
{
    PATH_MODE_NONE = 0,
    PATH_MODE_READ = 1 << 0,    ///< Handled by the VFS.
    PATH_MODE_WRITE = 1 << 1,   ///< Handled by the VFS.
    PATH_MODE_EXECUTE = 1 << 2, ///< Handled by the VFS.
    PATH_MODE_APPEND = 1 << 3,  ///< Should be implemented by the filesystem.
    /**
     * Handled by the VFS, if `PATH_MODE_DIRECTORY`, `PATH_MODE_SYMLINK` and `PATH_MODE_HARDLINK` are not specified,
     * then a `IRP_MJ_CREATE` handler should create a regular file.
     */
    PATH_MODE_CREATE = 1 << 4,
    PATH_MODE_DIRECTORY = 1 << 5, ///< Specifies what to create in a `IRP_MJ_CREATE` handler.
    PATH_MODE_SYMLINK = 1 << 6,   ///< Specifies what to create in a `IRP_MJ_CREATE` handler.
    PATH_MODE_HARDLINK = 1 << 7,  ///< Specifies what to create in a `IRP_MJ_CREATE` handler.
    PATH_MODE_EXCLUSIVE = 1 << 8, ///< Handled by the VFS.
    PATH_MODE_EXISTING = 1 << 9,  ///< Handled by the VFS.
    PATH_MODE_TRUNCATE = 1 << 10, ///< Should be implemented by the filesystem.
    PATH_MODE_NOFOLLOW = 1 << 11, ///< Handled by the VFS.
    PATH_MODE_PARENTS = 1 << 12,  ///< Handled by the VFS.
    PATH_MODE_LOCKED = 1 << 13,   ///< Handled by the VFS.
    PATH_MODE_ALL_PERMS = PATH_MODE_READ | PATH_MODE_WRITE | PATH_MODE_EXECUTE,
} path_mode_t;

/**
 * @brief Convert a path mode to a POSIX mode.
 *
 * @param mode The path mode to convert.
 * @return The resulting POSIX mode.
 */
mode_t path_mode_to_posix(path_mode_t mode);

/**
 * @brief Convert a POSIX mode to a path mode.
 *
 * @param mode The POSIX mode to convert.
 * @return The resulting path mode.
 */
path_mode_t path_posix_to_mode(mode_t mode);

/**
 * @brief Convert a path mode string to a POSIX mode.
 *
 * @param str The path mode string to convert.
 * @param length The length of the string.
 * @param out Output pointer to store the resulting POSIX mode.
 * @return An appropriate status value.
 */
status_t path_string_to_posix(const char* str, size_t length, mode_t* out);

/**
 * @brief Convert a POSIX mode to its path mode string representation.
 *
 * @param mode The POSIX mode to convert.
 * @param out The output string buffer.
 * @param length The length of the output string buffer.
 * @param outLength Output pointer to store the length of the resulting string.
 * @return An appropriate status value.
 */
status_t path_posix_to_string(mode_t mode, char* out, uint64_t length, uint64_t* outLength);

/**
 * @brief Convert a string to its path mode representation.
 *
 * @param str The path mode string to convert.
 * @param length The length of the string.
 * @param out Output pointer to store the resulting path mode.
 * @return An appropriate status value.
 */
status_t path_string_to_mode(const char* str, size_t length, path_mode_t* out);

/**
 * @brief Convert a path mode to its string representation.
 *
 * @param mode The path mode to convert.
 * @param out The output string buffer.
 * @param length The length of the output string buffer.
 * @param outLength Output pointer to store the length of the resulting string.
 * @return An appropriate status value.
 */
status_t path_mode_to_string(path_mode_t mode, char* out, uint64_t length, uint64_t* outLength);

/** @} */

#if defined(__cplusplus)
}
#endif

#endif
