#pragma once

#include <libgfx/gfx.h>

/**
 * @brief Theme definitions
 * @defgroup comp_libgui_theme Theme
 * @ingroup comp
 * 
 * The default theme is inspired by the Rosé Pine color palette.
 * 
 * @todo Dont hardcode colors and stuff, add in a theming system.
 * 
 * @see [https://rosepinetheme.com/](Rosé Pine)
 * 
 * @{
 */

#define _GUI_THEME_LOVE GFX_PIXEL(0xFF, 0xEB, 0x6F, 0x92)
#define _GUI_THEME_GOLD GFX_PIXEL(0xFF, 0xF6, 0xC1, 0x77)
#define _GUI_THEME_ROSE GFX_PIXEL(0xFF, 0xEB, 0xBC, 0xBA)
#define _GUI_THEME_PINE GFX_PIXEL(0xFF, 0x31, 0x74, 0x8F)
#define _GUI_THEME_FOAM GFX_PIXEL(0xFF, 0x9C, 0xCF, 0xBD)
#define _GUI_THEME_IRIS GFX_PIXEL(0xFF, 0xC4, 0xA7, 0xE7)

#define GUI_THEME_BASE GFX_PIXEL(0xFF, 0x19, 0x17, 0x24)
#define GUI_THEME_SURFACE GFX_PIXEL(0xFF, 0x1F, 0x1D, 0x2E)
#define GUI_THEME_OVERLAY GFX_PIXEL(0xFF, 0x26, 0x23, 0x3A)
#define GUI_THEME_MUTED GFX_PIXEL(0xFF, 0x6E, 0x6A, 0x86)
#define GUI_THEME_SUBTLE GFX_PIXEL(0xFF, 0x90, 0x8C, 0xAA)
#define GUI_THEME_TEXT GFX_PIXEL(0xFF, 0xE0, 0xDE, 0xF4)

#define GUI_THEME_HIGHLIGHT_LOW GFX_PIXEL(0xFF, 0x21, 0x20, 0x2E)
#define GUI_THEME_HIGHLIGHT_MED GFX_PIXEL(0xFF, 0x40, 0x3D, 0x52)
#define GUI_THEME_HIGHLIGHT_HIGH GFX_PIXEL(0xFF, 0x52, 0x4F, 0x67)

#define GUI_THEME_ERROR _GUI_THEME_LOVE
#define GUI_THEME_WARNING _GUI_THEME_GOLD
#define GUI_THEME_SUCCESS _GUI_THEME_PINE
#define GUI_THEME_INFO _GUI_THEME_FOAM

#define GUI_THEME_RED _GUI_THEME_LOVE
#define GUI_THEME_BRIGHT_RED _GUI_THEME_LOVE

#define GUI_THEME_YELLOW _GUI_THEME_GOLD
#define GUI_THEME_BRIGHT_YELLOW _GUI_THEME_GOLD

#define GUI_THEME_CYAN _GUI_THEME_ROSE
#define GUI_THEME_BRIGHT_CYAN _GUI_THEME_ROSE

#define GUI_THEME_GREEN _GUI_THEME_PINE
#define GUI_THEME_BRIGHT_GREEN _GUI_THEME_PINE

#define GUI_THEME_BLUE _GUI_THEME_FOAM
#define GUI_THEME_BRIGHT_BLUE _GUI_THEME_FOAM

#define GUI_THEME_MAGENTA _GUI_THEME_IRIS
#define GUI_THEME_BRIGHT_MAGENTA _GUI_THEME_IRIS

#define GUI_THEME_WINDOW_TITLEBAR GUI_THEME_OVERLAY
#define GUI_THEME_WINDOW_BORDER GUI_THEME_HIGHLIGHT_MED
#define GUI_THEME_WINDOW_BACKGROUND GUI_THEME_BASE

#define GUI_THEME_WIDGET_BACKGROUND GUI_THEME_SURFACE
#define GUI_THEME_WIDGET_BORDER GUI_THEME_HIGHLIGHT_LOW
#define GUI_THEME_WIDGET_TEXT GUI_THEME_TEXT

#define GUI_THEME_BUTTON_BACKGROUND GUI_THEME_OVERLAY
#define GUI_THEME_BUTTON_BORDER GUI_THEME_HIGHLIGHT_MED
#define GUI_THEME_BUTTON_TEXT GUI_THEME_TEXT
#define GUI_THEME_BUTTON_HOVER GUI_THEME_HIGHLIGHT_HIGH
#define GUI_THEME_BUTTON_ACTIVE GUI_THEME_HIGHLIGHT_LOW

#define GUI_THEME_WINDOW_TITLEBAR_HEIGHT 24
#define GUI_THEME_WINDOW_BORDER_WIDTH 1
#define GUI_THEME_WINDOW_RADIUS 24

#define GUI_THEME_WIDGET_PADDING 4
#define GUI_THEME_WIDGET_SPACING 4
#define GUI_THEME_WIDGET_RADIUS 2
#define GUI_THEME_WIDGET_BORDER_WIDTH 1

#define GUI_THEME_BUTTON_PADDING_H 8
#define GUI_THEME_BUTTON_PADDING_V 4
#define GUI_THEME_BUTTON_RADIUS 12
#define GUI_THEME_BUTTON_BORDER_WIDTH 1

/** @} */