#include <errno.h>
#include <libc/status.h>

int status_to_errno(status_t status)
{
    if (IS_INFO(status))
    {
        return EOK;
    }

    switch (STATUS_CODE(status))
    {
    case STATUS_CODE_NONE:
        return EOK;
    case STATUS_CODE_UNKNOWN:
    case STATUS_CODE_TEST_FAIL:
    case STATUS_CODE_RAND:
        return EIO;
    case STATUS_CODE_INVAL:
    case STATUS_CODE_NOT_CANCELLABLE:
    case STATUS_CODE_INVALFLAG:
    case STATUS_CODE_ARGC:
    case STATUS_CODE_ALIGN:
    case STATUS_CODE_UNMAPPED:
    case STATUS_CODE_INVALCHAR:
    case STATUS_CODE_EXPECT_FILE:
    case STATUS_CODE_NOT_INIT:
    case STATUS_CODE_INVAL_ACPI_TABLE:
    case STATUS_CODE_NO_BOOT_INFO:
    case STATUS_CODE_NOVERSION:
    case STATUS_CODE_INVALSCON:
    case STATUS_CODE_MJ_INVAL:
        return EINVAL;
    case STATUS_CODE_OVERFLOW:
    case STATUS_CODE_MJ_OVERFLOW:
        return EOVERFLOW;
    case STATUS_CODE_TOOBIG:
        return E2BIG;
    case STATUS_CODE_TIMEOUT:
        return ETIMEDOUT;
    case STATUS_CODE_CANCELLED:
        return ECANCELED;
    case STATUS_CODE_IMPL:
    case STATUS_CODE_MJ_NOSYS:
        return ENOSYS;
    case STATUS_CODE_AGAIN:
    case STATUS_CODE_CHANGED:
        return EAGAIN;
    case STATUS_CODE_INTR:
        return EINTR;
    case STATUS_CODE_FULL:
    case STATUS_CODE_NOSPACE:
        return ENOSPC;
    case STATUS_CODE_NOMEM:
    case STATUS_CODE_SHARED_LIMIT:
        return ENOMEM;
    case STATUS_CODE_FAULT:
    case STATUS_CODE_IN_STACK:
        return EFAULT;
    case STATUS_CODE_PATHTOOLONG:
    case STATUS_CODE_NAMETOOLONG:
        return ENAMETOOLONG;
    case STATUS_CODE_FD_OVERFLOW:
    case STATUS_CODE_MFILE:
        return EMFILE;
    case STATUS_CODE_BADFD:
        return EBADF;
    case STATUS_CODE_NOENT:
    case STATUS_CODE_NEGATIVE:
    case STATUS_CODE_NOINTERP:
        return ENOENT;
    case STATUS_CODE_NOTDIR:
        return ENOTDIR;
    case STATUS_CODE_ISDIR:
        return EISDIR;
    case STATUS_CODE_BUSY:
    case STATUS_CODE_TOCTOU:
    case STATUS_CODE_PINNED:
    case STATUS_CODE_ACQUIRED:
        return EBUSY;
    case STATUS_CODE_EXIST:
    case STATUS_CODE_MAPPED:
    case STATUS_CODE_ALREADY_INIT:
        return EEXIST;
    case STATUS_CODE_XDEV:
        return EXDEV;
    case STATUS_CODE_NOTEMPTY:
        return ENOTEMPTY;
    case STATUS_CODE_IO:
        return EIO;
    case STATUS_CODE_SHADOW_LIMIT:
    case STATUS_CODE_LOOP:
        return ELOOP;
    case STATUS_CODE_NOFS:
    case STATUS_CODE_NODEV:
    case STATUS_CODE_NO_ACPI_TABLE:
        return ENODEV;
    case STATUS_CODE_SPIPE:
        return ESPIPE;
    case STATUS_CODE_ADDRINUSE:
        return EADDRINUSE;
    case STATUS_CODE_INVALCTL:
    case STATUS_CODE_NOTTY:
        return ENOTTY;
    case STATUS_CODE_NOSUPPORT:
        return EOPNOTSUPP;
    case STATUS_CODE_ACCESS:
    case STATUS_CODE_NOGROUP:
        return EACCES;
    case STATUS_CODE_PERM:
        return EPERM;
    case STATUS_CODE_INVAL_KEY:
        return EKEYREJECTED;
    case STATUS_CODE_DOTDOT:
        return EDOTDOT;
    case STATUS_CODE_DYING:
    case STATUS_CODE_NOT_RUNNING:
        return ESRCH;
    case STATUS_CODE_DEADLOCK:
        return EDEADLK;
    case STATUS_CODE_RUNNING:
        return EALREADY;
    case STATUS_CODE_INVALELF:
        return ENOEXEC;
    case STATUS_CODE_ILSEQ:
        return EILSEQ;
    default:
        return EIO;
    }
}