#include "aml_token.h"

#include <stdlib.h>

const aml_token_props_t amlTokenProps[AML_MAX_TOKEN] = {
    // Normal Opcodes (0x00-0xFF)
    [AML_ZERO_OP] = {"ZeroOp", AML_ENCODING_GROUP_DATA, AML_TOKEN_TYPE_COMPUTATIONAL},
    [AML_ONE_OP] = {"OneOp", AML_ENCODING_GROUP_DATA, AML_TOKEN_TYPE_COMPUTATIONAL},
    [AML_ALIAS_OP] = {"AliasOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_NAMESPACE_MODIFIER},
    [AML_NAME_OP] = {"NameOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_NAMESPACE_MODIFIER},
    [AML_BYTE_PREFIX] = {"BytePrefix", AML_ENCODING_GROUP_DATA, AML_TOKEN_TYPE_COMPUTATIONAL},
    [AML_WORD_PREFIX] = {"WordPrefix", AML_ENCODING_GROUP_DATA, AML_TOKEN_TYPE_COMPUTATIONAL},
    [AML_DWORD_PREFIX] = {"DWordPrefix", AML_ENCODING_GROUP_DATA, AML_TOKEN_TYPE_COMPUTATIONAL},
    [AML_STRING_PREFIX] = {"StringPrefix", AML_ENCODING_GROUP_DATA, AML_TOKEN_TYPE_COMPUTATIONAL},
    [AML_QWORD_PREFIX] = {"QWordPrefix", AML_ENCODING_GROUP_DATA, AML_TOKEN_TYPE_COMPUTATIONAL},
    [AML_SCOPE_OP] = {"ScopeOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_NAMESPACE_MODIFIER},
    [AML_BUFFER_OP] = {"BufferOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_EXPRESSION},
    [AML_PACKAGE_OP] = {"PackageOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_EXPRESSION},
    [AML_VAR_PACKAGE_OP] = {"VarPackageOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_EXPRESSION},
    [AML_METHOD_OP] = {"MethodOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_NAMED},
    [AML_EXTERNAL_OP] = {"ExternalOp", AML_ENCODING_GROUP_NAME, AML_TOKEN_TYPE_NAMED},
    [AML_DUAL_NAME_PREFIX] = {"DualNamePrefix", AML_ENCODING_GROUP_NAME, AML_TOKEN_TYPE_NAME},
    [AML_MULTI_NAME_PREFIX] = {"MultiNamePrefix", AML_ENCODING_GROUP_NAME, AML_TOKEN_TYPE_NAME},
    [AML_DIGIT_CHAR_0... AML_DIGIT_CHAR_9] = {"DigitChar", AML_ENCODING_GROUP_NAME, AML_TOKEN_TYPE_NAME},
    [AML_NAME_CHAR_A... AML_NAME_CHAR_Z] = {"NameChar", AML_ENCODING_GROUP_NAME, AML_TOKEN_TYPE_NAME},
    [AML_EXT_OP_PREFIX] = {"ExtOpPrefix", AML_ENCODING_GROUP_NONE, AML_TOKEN_TYPE_NONE},
    [AML_ROOT_CHAR] = {"RootChar", AML_ENCODING_GROUP_NAME, AML_TOKEN_TYPE_NAME},
    [AML_PARENT_PREFIX_CHAR] = {"ParentPrefixChar", AML_ENCODING_GROUP_NAME, AML_TOKEN_TYPE_NAME},
    [AML_NAME_CHAR] = {"NameChar", AML_ENCODING_GROUP_NAME, AML_TOKEN_TYPE_NAME},
    [AML_LOCAL0_OP] = {"Local0Op", AML_ENCODING_GROUP_LOCAL, AML_TOKEN_TYPE_LOCAL},
    [AML_LOCAL1_OP] = {"Local1Op", AML_ENCODING_GROUP_LOCAL, AML_TOKEN_TYPE_LOCAL},
    [AML_LOCAL2_OP] = {"Local2Op", AML_ENCODING_GROUP_LOCAL, AML_TOKEN_TYPE_LOCAL},
    [AML_LOCAL3_OP] = {"Local3Op", AML_ENCODING_GROUP_LOCAL, AML_TOKEN_TYPE_LOCAL},
    [AML_LOCAL4_OP] = {"Local4Op", AML_ENCODING_GROUP_LOCAL, AML_TOKEN_TYPE_LOCAL},
    [AML_LOCAL5_OP] = {"Local5Op", AML_ENCODING_GROUP_LOCAL, AML_TOKEN_TYPE_LOCAL},
    [AML_LOCAL6_OP] = {"Local6Op", AML_ENCODING_GROUP_LOCAL, AML_TOKEN_TYPE_LOCAL},
    [AML_LOCAL7_OP] = {"Local7Op", AML_ENCODING_GROUP_LOCAL, AML_TOKEN_TYPE_LOCAL},
    [AML_ARG0_OP] = {"Arg0Op", AML_ENCODING_GROUP_ARG, AML_TOKEN_TYPE_ARG},
    [AML_ARG1_OP] = {"Arg1Op", AML_ENCODING_GROUP_ARG, AML_TOKEN_TYPE_ARG},
    [AML_ARG2_OP] = {"Arg2Op", AML_ENCODING_GROUP_ARG, AML_TOKEN_TYPE_ARG},
    [AML_ARG3_OP] = {"Arg3Op", AML_ENCODING_GROUP_ARG, AML_TOKEN_TYPE_ARG},
    [AML_ARG4_OP] = {"Arg4Op", AML_ENCODING_GROUP_ARG, AML_TOKEN_TYPE_ARG},
    [AML_ARG5_OP] = {"Arg5Op", AML_ENCODING_GROUP_ARG, AML_TOKEN_TYPE_ARG},
    [AML_ARG6_OP] = {"Arg6Op", AML_ENCODING_GROUP_ARG, AML_TOKEN_TYPE_ARG},
    [AML_STORE_OP] = {"StoreOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_EXPRESSION},
    [AML_REF_OF_OP] = {"RefOfOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_EXPRESSION},
    [AML_ADD_OP] = {"AddOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_EXPRESSION},
    [AML_CONCAT_OP] = {"ConcatOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_EXPRESSION},
    [AML_SUBTRACT_OP] = {"SubtractOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_EXPRESSION},
    [AML_INCREMENT_OP] = {"IncrementOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_EXPRESSION},
    [AML_DECREMENT_OP] = {"DecrementOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_EXPRESSION},
    [AML_MULTIPLY_OP] = {"MultiplyOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_EXPRESSION},
    [AML_DIVIDE_OP] = {"DivideOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_EXPRESSION},
    [AML_SHIFT_LEFT_OP] = {"ShiftLeftOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_EXPRESSION},
    [AML_SHIFT_RIGHT_OP] = {"ShiftRightOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_EXPRESSION},
    [AML_AND_OP] = {"AndOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_EXPRESSION},
    [AML_NAND_OP] = {"NandOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_EXPRESSION},
    [AML_OR_OP] = {"OrOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_EXPRESSION},
    [AML_NOR_OP] = {"NorOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_EXPRESSION},
    [AML_XOR_OP] = {"XorOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_EXPRESSION},
    [AML_NOT_OP] = {"NotOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_EXPRESSION},
    [AML_FIND_SET_LEFT_BIT_OP] = {"FindSetLeftBitOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_EXPRESSION},
    [AML_FIND_SET_RIGHT_BIT_OP] = {"FindSetRightBitOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_EXPRESSION},
    [AML_DEREF_OF_OP] = {"DerefOfOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_EXPRESSION},
    [AML_CONCAT_RES_OP] = {"ConcatResOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_EXPRESSION},
    [AML_MOD_OP] = {"ModOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_EXPRESSION},
    [AML_NOTIFY_OP] = {"NotifyOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_STATEMENT},
    [AML_SIZE_OF_OP] = {"SizeOfOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_EXPRESSION},
    [AML_INDEX_OP] = {"IndexOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_EXPRESSION},
    [AML_MATCH_OP] = {"MatchOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_EXPRESSION},
    [AML_CREATE_DWORD_FIELD_OP] = {"CreateDWordFieldOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_NAMED},
    [AML_CREATE_WORD_FIELD_OP] = {"CreateWordFieldOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_NAMED},
    [AML_CREATE_BYTE_FIELD_OP] = {"CreateByteFieldOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_NAMED},
    [AML_CREATE_BIT_FIELD_OP] = {"CreateBitFieldOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_NAMED},
    [AML_OBJECT_TYPE_OP] = {"ObjectTypeOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_EXPRESSION},
    [AML_CREATE_QWORD_FIELD_OP] = {"CreateQWordFieldOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_NAMED},
    [AML_LAND_OP] = {"LandOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_EXPRESSION},
    [AML_LOR_OP] = {"LorOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_EXPRESSION},
    [AML_LNOT_OP] = {"LnotOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_EXPRESSION},
    [AML_LEQUAL_OP] = {"LEqualOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_EXPRESSION},
    [AML_LGREATER_OP] = {"LGreaterOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_EXPRESSION},
    [AML_LLESS_OP] = {"LLessOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_EXPRESSION},
    [AML_TO_BUFFER_OP] = {"ToBufferOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_EXPRESSION},
    [AML_TO_DECIMAL_STRING_OP] = {"ToDecimalStringOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_EXPRESSION},
    [AML_TO_HEX_STRING_OP] = {"ToHexStringOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_EXPRESSION},
    [AML_TO_INTEGER_OP] = {"ToIntegerOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_EXPRESSION},
    [AML_TO_STRING_OP] = {"ToStringOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_EXPRESSION},
    [AML_COPY_OBJECT_OP] = {"CopyObjectOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_EXPRESSION},
    [AML_MID_OP] = {"MidOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_EXPRESSION},
    [AML_CONTINUE_OP] = {"ContinueOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_STATEMENT},
    [AML_IF_OP] = {"IfOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_STATEMENT},
    [AML_ELSE_OP] = {"ElseOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_STATEMENT},
    [AML_WHILE_OP] = {"WhileOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_STATEMENT},
    [AML_NOOP_OP] = {"NoopOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_STATEMENT},
    [AML_RETURN_OP] = {"ReturnOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_STATEMENT},
    [AML_BREAK_OP] = {"BreakOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_STATEMENT},
    [AML_BREAK_POINT_OP] = {"BreakPointOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_STATEMENT},
    [AML_ONES_OP] = {"OnesOp", AML_ENCODING_GROUP_DATA, AML_TOKEN_TYPE_COMPUTATIONAL},

    // Extended Opcodes (prefixed with 0x5B)
    [AML_MUTEX_OP] = {"MutexOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_NAMED},
    [AML_EVENT_OP] = {"EventOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_NAMED},
    [AML_COND_REF_OF_OP] = {"CondRefOfOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_EXPRESSION},
    [AML_CREATE_FIELD_OP] = {"CreateFieldOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_NAMED},
    [AML_LOAD_TABLE_OP] = {"LoadTableOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_EXPRESSION},
    [AML_LOAD_OP] = {"LoadOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_EXPRESSION},
    [AML_STALL_OP] = {"StallOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_STATEMENT},
    [AML_SLEEP_OP] = {"SleepOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_STATEMENT},
    [AML_ACQUIRE_OP] = {"AcquireOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_EXPRESSION},
    [AML_SIGNAL_OP] = {"SignalOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_STATEMENT},
    [AML_WAIT_OP] = {"WaitOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_EXPRESSION},
    [AML_RESET_OP] = {"ResetOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_STATEMENT},
    [AML_RELEASE_OP] = {"ReleaseOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_STATEMENT},
    [AML_FROM_BCD_OP] = {"FromBCDOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_EXPRESSION},
    [AML_TO_BCD_OP] = {"ToBCD", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_EXPRESSION},
    [AML_RESERVED_OP] = {"Reserved", AML_ENCODING_GROUP_NONE, AML_TOKEN_TYPE_NONE},
    [AML_REVISION_OP] = {"RevisionOp", AML_ENCODING_GROUP_DATA, AML_TOKEN_TYPE_COMPUTATIONAL},
    [AML_DEBUG_OP] = {"DebugOp", AML_ENCODING_GROUP_DEBUG, AML_TOKEN_TYPE_DEBUG},
    [AML_FATAL_OP] = {"FatalOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_STATEMENT},
    [AML_TIMER_OP] = {"TimerOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_EXPRESSION},
    [AML_OPREGION_OP] = {"OpRegionOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_NAMED},
    [AML_FIELD_OP] = {"FieldOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_NAMED},
    [AML_DEVICE_OP] = {"DeviceOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_NAMED},
    [AML_DEPRECATED_PROCESSOR_OP] = {"DeprecatedProcessorOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_NAMED},
    [AML_POWER_RES_OP] = {"PowerResOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_NAMED},
    [AML_THERMAL_ZONE_OP] = {"ThermalZoneOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_NAMED},
    [AML_INDEX_FIELD_OP] = {"IndexFieldOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_NAMED},
    [AML_BANK_FIELD_OP] = {"BankFieldOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_NAMED},
    [AML_REGION_OP] = {"DataRegionOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_NAMED},

    // Extended Opcodes (prefixed with 0x92)
    [AML_LNOT_EQUAL_OP] = {"LNotEqualOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_EXPRESSION},
    [AML_LLESS_EQUAL_OP] = {"LLessEqualOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_EXPRESSION},
    [AML_LGREATER_EQUAL_OP] = {"LGreaterEqualOp", AML_ENCODING_GROUP_TERM, AML_TOKEN_TYPE_EXPRESSION},

    [AML_UNKNOWN_TOKEN] = {"UnknownToken", AML_ENCODING_GROUP_NONE, AML_TOKEN_TYPE_NONE},
};

const char* aml_token_type_to_string(aml_token_type_t type)
{
    switch (type)
    {
    case AML_TOKEN_TYPE_NAMESPACE_MODIFIER:
        return "NamespaceModifier";
    case AML_TOKEN_TYPE_NAME:
        return "Name";
    case AML_TOKEN_TYPE_NAMED:
        return "Named";
    case AML_TOKEN_TYPE_STATEMENT:
        return "Statement";
    case AML_TOKEN_TYPE_EXPRESSION:
        return "Expression";
    case AML_TOKEN_TYPE_ARG:
        return "Arg";
    case AML_TOKEN_TYPE_LOCAL:
        return "Local";
    case AML_TOKEN_TYPE_COMPUTATIONAL:
        return "Computational";
    case AML_TOKEN_TYPE_DEBUG:
        return "Debug";
    default:
        return "UnknownToken";
    }
}
