#include <sys/status.h>

const char* _codeStrings[] = {
    [ST_CODE_NONE] = "no specific code",
    [ST_CODE_UNKNOWN] = "unknown error",
    [ST_CODE_INVAL] = "invalid argument",
    [ST_CODE_OVERFLOW] = "buffer overflow",
    [ST_CODE_TOOBIG] = "value too big",
    [ST_CODE_NOMEM] = "out of memory",
    [ST_CODE_TIMEOUT] = "operation timed out",
    [ST_CODE_NOSPACE] = "no space left",
    [ST_CODE_MJ_OVERFLOW] = "major number overflow",
    [ST_CODE_MJ_NOSYS] = "major number not found",
    [ST_CODE_CANCELLED] = "operation cancelled",
    [ST_CODE_NOT_CANCELLABLE] = "operation cannot be cancelled",
    [ST_CODE_FAULT] = "bad address",
    [ST_CODE_DYING] = "process is dying",
    [ST_CODE_ACCESS] = "permission denied",
    [ST_CODE_ALIGN] = "alignment error",
    [ST_CODE_MAPPED] = "already mapped",
    [ST_CODE_UNMAPPED] = "not mapped",
    [ST_CODE_PINNED] = "page pinned",
    [ST_CODE_SHARED_LIMIT] = "shared memory limit reached",
    [ST_CODE_IN_STACK] = "address in stack",
    [ST_CODE_IMPL] = "implementation error",
    [ST_CODE_AGAIN] = "resource temporarily unavailable",
    [ST_CODE_INTR] = "interrupted system call",
    [ST_CODE_PATHTOOLONG] = "path too long",
    [ST_CODE_NAMETOOLONG] = "name too long",
    [ST_CODE_INVALCHAR] = "invalid character",
    [ST_CODE_INVALFLAG] = "invalid flag",
    [ST_CODE_CHANGED] = "state changed",
    [ST_CODE_FULL] = "buffer full",
    [ST_CODE_MORE] = "more data available",
    [ST_CODE_FD_OVERFLOW] = "file descriptor overflow",
    [ST_CODE_MFILE] = "too many open files",
    [ST_CODE_BADFD] = "bad file descriptor",
    [ST_CODE_RAND] = "random number generator error",
    [ST_CODE_NOENT] = "no such file or directory",
    [ST_CODE_NOTDIR] = "not a directory",
    [ST_CODE_ISDIR] = "is a directory",
    [ST_CODE_BUSY] = "device or resource busy",
    [ST_CODE_EXIST] = "file exists",
    [ST_CODE_XDEV] = "cross-device link",
    [ST_CODE_NOTEMPTY] = "directory not empty",
    [ST_CODE_NODEV] = "no such device",
    [ST_CODE_IO] = "i/o error",
    [ST_CODE_SHADOW_LIMIT] = "shadow mount limit reached",
    [ST_CODE_LOOP] = "too many symbolic links",
    [ST_CODE_NOFS] = "no filesystem found",
    [ST_CODE_NEGATIVE] = "path component does not exist",
    [ST_CODE_ARGC] = "invalid argument count",
    [ST_CODE_INVALCTL] = "invalid control command",
    [ST_CODE_NOGROUP] = "not within a group",
    [ST_CODE_PERM] = "operation not permitted",
    [ST_CODE_NOTTY] = "inappropriate ioctl for device",
    [ST_CODE_SPIPE] = "invalid seek",
    [ST_CODE_MCLOCK] = "too many clock sources",
    [ST_CODE_TOCTOU] = "time-of-check to time-of-use race condition",
    [ST_CODE_INVALELF] = "invalid elf executable",
    [ST_CODE_NOT_INIT] = "resource is not initialized",
    [ST_CODE_ALREADY_INIT] = "resource is already initialized",
    [ST_CODE_ACQUIRED] = "resource is already acquired",
    [ST_CODE_MTIMER] = "to many timer sources",
    [ST_CODE_ILSEQ] = "invalid byte sequence",
    [ST_CODE_NO_ACPI_TABLE] = "unable to locate acpu table",
    [ST_CODE_INVAL_ACPI_TABLE] = "invalid acpi table",
    [ST_CODE_DEADLOCK] = "deadlock detected",
    [ST_CODE_NO_BOOT_INFO] = "bootloader did not provide needed info",
    [ST_CODE_ADDRINUSE] = "address already in use",
};

const char* codetostr(st_code_t code)
{
    if (code < ST_CODE_NONE || code > ST_CODE_ADDRINUSE)
    {
        return "unknown";
    }
    return _codeStrings[code];
}