set(CMAKE_SYSTEM_NAME PatchworkOS)
set(CMAKE_SYSTEM_PROCESSOR x86_64)

set(CMAKE_FIND_LIBRARY_PREFIXES "lib" "")
set(CMAKE_FIND_LIBRARY_SUFFIXES ".so" ".a" "")
set(CMAKE_STATIC_LIBRARY_PREFIX "lib")
set(CMAKE_STATIC_LIBRARY_SUFFIX ".a")
set(CMAKE_SHARED_LIBRARY_PREFIX "lib")
set(CMAKE_SHARED_LIBRARY_SUFFIX ".so")
set(CMAKE_SHARED_LIBRARY_SONAME_C_FLAG "-Wl,-soname,")
set(CMAKE_SHARED_LIBRARY_SONAME_CXX_FLAG "-Wl,-soname,")
set(CMAKE_EXECUTABLE_SUFFIX "")
set(CMAKE_SYSTEM_PREFIX_PATH "/")

set(CMAKE_MODULE_PATH "${CMAKE_CURRENT_LIST_DIR}" CACHE PATH "CMake module path" FORCE)

set(CMAKE_C_COMPILER clang)
set(CMAKE_CXX_COMPILER clang++)
set(CMAKE_ASM_COMPILER clang)

set(CMAKE_C_FLAGS_INIT "--config ${CMAKE_CURRENT_LIST_DIR}/patchworkos.cfg")
set(CMAKE_CXX_FLAGS_INIT "--config ${CMAKE_CURRENT_LIST_DIR}/patchworkos.cfg")
set(CMAKE_ASM_FLAGS_INIT "--config ${CMAKE_CURRENT_LIST_DIR}/patchworkos.cfg")

set(PATCHWORKOS_LINK_FLAGS "-nostdlib -L${CMAKE_CURRENT_LIST_DIR}/../build/staging/lib -Wl,-dynamic-linker=/lib/dynlink.so -Wl,--image-base=0x400000 ${CMAKE_CURRENT_LIST_DIR}/../bin/comp/crt0.o ${CMAKE_CURRENT_LIST_DIR}/../bin/comp/crti.o")
set(CMAKE_EXE_LINKER_FLAGS_INIT "${PATCHWORKOS_LINK_FLAGS}")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "-nostdlib -L${CMAKE_CURRENT_LIST_DIR}/../build/staging/lib ${CMAKE_CURRENT_LIST_DIR}/../bin/comp/crti.o")

set(PATCHWORKOS_STANDARD_LIBRARIES "-lc ${CMAKE_CURRENT_LIST_DIR}/../bin/comp/crtn.o")
set(CMAKE_C_STANDARD_LIBRARIES_INIT "${PATCHWORKOS_STANDARD_LIBRARIES}")
set(CMAKE_CXX_STANDARD_LIBRARIES_INIT "${PATCHWORKOS_STANDARD_LIBRARIES}")
set(CMAKE_ASM_STANDARD_LIBRARIES_INIT "${PATCHWORKOS_STANDARD_LIBRARIES}")

set(CMAKE_AR llvm-ar)
set(CMAKE_RANLIB llvm-ranlib)
set(CMAKE_LINKER ld.lld)

set(CMAKE_SYSROOT "${CMAKE_CURRENT_LIST_DIR}/../build/staging")
set(CMAKE_FIND_ROOT_PATH "${CMAKE_CURRENT_LIST_DIR}/../build/staging")

set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
