#!/bin/bash

SCRIPT_DIR="${BASH_SOURCE[0]%/*}"

gcc -march=x86-64 \
  -nostdlib \
  -nostdinc \
  -ffreestanding \
  -fno-builtin \
  -isystem "$SCRIPT_DIR/../include" \
  -isystem "$SCRIPT_DIR/../include/libstd" \
  -L"$SCRIPT_DIR/../bin/libstd" \
  -L"$SCRIPT_DIR/../bin/libpatchwork" \
  "$@"