#define SYS_TEST 0
#define SYS_YIELD 1
#define SYS_EXIT 2
#define SYS_AMOUNT 2

#define ADDRESS_SPACE_INTERRUPT_STACK 0x3FFFFFF000

#define TASK_STATE_RUNNING 0
#define TASK_STATE_READY 1
#define TASK_STATE_WAITING 2

#define EXIT_FAILURE 1
#define EXIT_SUCCESS 0

#define OS_VERSION "Patchwork OS"