#pragma once

#define THEME_EDGE_WIDTH 4
#define THEME_HIGHLIGHT 0xFFFEFEFE
#define THEME_SHADOW 0xFF3C3C3C
#define THEME_BACKGROUND 0xFFBFBFBF
#define THEME_TOPBAR_HIGHLIGHT 0xFF00007F
#define THEME_TOPBAR_SHADOW 0xFF7F7F7F
#define THEME_TOPBAR_HEIGHT 32
