#ifndef _SYS_FS_H
#define _SYS_FS_H 1

#include <alloca.h>
#include <assert.h>
#include <errno.h>
#include <stdarg.h>
#include <stdint.h>
#include <stdlib.h>
#include <sys/status.h>
#include <sys/syscall.h>

#if defined(__cplusplus)
extern "C"
{
#endif

#include "_libstd/MAX_NAME.h"
#include "_libstd/MAX_PATH.h"
#include "_libstd/NULL.h"
#include "_libstd/clock_t.h"
#include "_libstd/config.h"
#include "_libstd/ssize_t.h"
#include "_libstd/time_t.h"

/**
 * @brief Filesystem interface.
 * @defgroup libstd_sys_fs Filesystem
 * @ingroup libstd
 *
 * @{
 */

#define KEYMAX 128 ///< Maximum size of a key generated by `fdshare()`.
#define KEY128 25  ///< The size of a buffer needed to hold a 128-bit key.
#define KEY256 45  ///< The size of a buffer needed to hold a 256-bit key.
#define KEY512 89  ///< The size of a buffer needed to hold a 512-bit key.

typedef uint64_t fd_t;      ///< File descriptor type.
#define FDIN ((fd_t)0)      ///< Standard input file descriptor.
#define FDOUT ((fd_t)1)     ///< Standard output file descriptor.
#define FDERR ((fd_t)2)     ///< Standard error file descriptor.
#define FDCWD ((fd_t)3)     ///< Standard current working directory file descriptor.
#define FDNONE ((fd_t) - 1) ///< No file descriptor.

/**
 * @brief System call for sharing a file descriptor with another process.
 *
 * @param fd The file descriptor to share.
 * @param key Output buffer to store the generated key.
 * @param size The size of the output buffer.
 * @param timeout The time until the shared file descriptor expires. If `CLOCKS_NEVER`, it never expires.
 * @return An appropriate status value.
 */
static inline status_t fdshare(fd_t fd, char* key, size_t size, clock_t timeout)
{
    return syscall4(SYS_FD_SHARE, NULL, fd, (uintptr_t)key, size, timeout);
}

/**
 * @brief System call for claiming a shared file descriptor.
 *
 * After claiming a shared file descriptor, the key is no longer valid and cannot be used again.
 *
 * @param out Output pointer to store the claimed file descriptor.
 * @param key The key identifying the shared file descriptor.
 * @return An appropriate status value.
 */
static inline status_t fdclaim(fd_t* out, const char* key)
{
    return syscall1(SYS_FD_CLAIM, out, (uintptr_t)key);
}

/**
 * @brief System call for duplicating file descriptors.
 *
 * @param src The open file descriptor to duplicate.
 * @param dest Output pointer for the new file descriptor, if `FDNONE` any free file descriptor will be used,
 * otherwise the specified file descriptor will be used.
 * @return An appropriate status value.
 */
static inline status_t fddup(fd_t src, fd_t* dest)
{
    return syscall2(SYS_FD_DUP, dest, src, *dest);
}

typedef uint16_t file_type_t;  ///< File type enum.
#define FILE_TYPE_UNKNOWN 0    ///< Unknown file type.
#define FILE_TYPE_REGULAR 1    ///< Regular file.
#define FILE_TYPE_DIRECTORY 3  ///< Directory.
#define FILE_TYPE_SYMLINK 4    ///< Symbolic link.
#define FILE_TYPE_DEVICE 5     ///< Device file.
#define FILE_TYPE_SYSTEM 6     ///< System file, used for exposing kernel information to user space.
#define FILE_TYPE_FILESYSTEM 7 ///< Filesystem file.

typedef uint16_t file_attr_t; ///< File attribute operations.
#define FILE_ATTR_IS_SET(attr) ((attr) & 1)
#define FILE_ATTR_IS_GET(attr) (!((attr) & 1))
#define _FILE_ATTR_GET(x) (((x) << 1) & ~1)
#define _FILE_ATTR_SET(x) (((x) << 1) | 1)
#define FILE_GET_SIZE _FILE_ATTR_GET(0)       ///< Get the size of the file.
#define FILE_SET_SIZE _FILE_ATTR_SET(0)       ///< Set the size of the file.
#define FILE_GET_BLOCKS _FILE_ATTR_GET(1)     ///< Get the number of blocks allocated.
#define FILE_GET_BLOCK_SIZE _FILE_ATTR_GET(2) ///< Get the block size.
#define FILE_GET_MAX_SIZE _FILE_ATTR_GET(3)   ///< Get the maximum file size.
#define FILE_GET_ATIME _FILE_ATTR_GET(4)      ///< Get the access time.
#define FILE_SET_ATIME _FILE_ATTR_SET(4)      ///< Set the access time.
#define FILE_GET_MTIME _FILE_ATTR_GET(5)      ///< Get the modification time.
#define FILE_SET_MTIME _FILE_ATTR_SET(5)      ///< Set the modification time.
#define FILE_GET_CTIME _FILE_ATTR_GET(6)      ///< Get the change time.
#define FILE_SET_CTIME _FILE_ATTR_SET(6)      ///< Set the change time.
#define FILE_GET_BTIME _FILE_ATTR_GET(7)      ///< Get the birth time.
#define FILE_SET_BTIME _FILE_ATTR_SET(7)      ///< Set the birth time.
#define FILE_GET_NUM _FILE_ATTR_GET(8)        ///< Get the file number.
#define FILE_GET_VOL _FILE_ATTR_GET(9)        ///< Get the volume ID.
#define FILE_GET_NLINK _FILE_ATTR_GET(10)     ///< Get the number of hard links.
#define FILE_GET_TYPE _FILE_ATTR_GET(11)      ///< Get the file type.

typedef uint64_t file_mask_t;         ///< Bitmask of which fields are valid within a `file_info_t` structure.
#define FILE_MASK_SIZE (1 << 0)       ///< File size is valid.
#define FILE_MASK_BLOCKS (1 << 1)     ///< Blocks allocated is valid.
#define FILE_MASK_BLOCK_SIZE (1 << 2) ///< Block size is valid.
#define FILE_MASK_MAX_SIZE (1 << 3)   ///< Maximum file size is valid.
#define FILE_MASK_ATIME (1 << 4)      ///< Access time is valid.
#define FILE_MASK_MTIME (1 << 5)      ///< Modification time is valid.
#define FILE_MASK_CTIME (1 << 6)      ///< Change time is valid.
#define FILE_MASK_BTIME (1 << 7)      ///< Birth/Creation time is valid.
#define FILE_MASK_NUM (1 << 8)        ///< File number is valid.
#define FILE_MASK_VOL (1 << 9)        ///< Volume ID is valid.
#define FILE_MASK_NLINK (1 << 10)     ///< Number of hard links is valid.
#define FILE_MASK_FLAGS (1 << 11)     ///< File flags are valid.
#define FILE_MASK_TYPE (1 << 12)      ///< File type is valid.
#define FILE_MASK_NAME (1 << 13)      ///< File name is valid.
#define FILE_MASK_MODE (1 << 14)      ///< File mode is valid.

/**
 * @brief File information structure.
 * @struct file_info_t
 */
typedef struct file_info
{
    file_mask_t valid;   ///< Bitmask of which fields are valid.
    size_t size;         ///< File size in bytes.
    size_t blocks;       ///< Blocks allocated.
    size_t blockSize;    ///< Block size in bytes.
    size_t maxSize;      ///< Maximum file size.
    clock_t atime;       ///< Access time (ns).
    clock_t mtime;       ///< Modification time (ns).
    clock_t ctime;       ///< Change time (ns).
    clock_t btime;       ///< Birth/Creation time (ns).
    uint64_t num;        ///< File number, depends on the file system, for example, inode number in ext4.
    uint64_t vol;        ///< Volume ID.
    uint32_t nlink;      ///< Number of hard links.
    file_type_t type;    ///< File type.
    char name[MAX_PATH]; ///< File name.
    char mode[MAX_NAME]; ///< File mode represented by their short-hand.
    uint8_t _reserved[123];
} file_info_t;

#ifdef static_assert
static_assert(sizeof(file_info_t) == 512, "file_info_t is not 512 bytes");
#endif

typedef uint64_t whence_t;           ///< Seek origin type.
#define WHENCE_START ((whence_t)0)   ///< Seek from the beginning of the file.
#define WHENCE_CURRENT ((whence_t)1) ///< Seek from the current position.
#define WHENCE_END ((whence_t)2)     ///< Seek from the end of the file.

typedef uint64_t events_t;    ///< Events type.
#define EVENTS_READ (1 << 0)  ///< File descriptor is ready to be read from.
#define EVENTS_WRITE (1 << 1) ///< File descriptor is ready to be written to.
#define EVENTS_ERROR (1 << 2) ///< File descriptor caused an error.
#define EVENTS_HUP (1 << 3)   ///< File descriptor is closed.
#define EVENTS_NVAL (1 << 4)  ///< Invalid file descriptor.

/** @} */

#if defined(__cplusplus)
}
#endif

#endif
