#ifndef _SYS_FS_H
#define _SYS_FS_H 1

#include <alloca.h>
#include <assert.h>
#include <errno.h>
#include <stdarg.h>
#include <stdint.h>
#include <stdlib.h>
#include <sys/status.h>
#include <sys/syscall.h>

#if defined(__cplusplus)
extern "C"
{
#endif

#include "_libstd/MAX_NAME.h"
#include "_libstd/MAX_PATH.h"
#include "_libstd/NULL.h"
#include "_libstd/clock_t.h"
#include "_libstd/config.h"
#include "_libstd/ssize_t.h"
#include "_libstd/time_t.h"

/**
 * @brief Filesystem interface.
 * @defgroup libstd_sys_fs Filesystem
 * @ingroup libstd
 *
 * @{
 */

#define FDKEY_MAX 128 ///< Maximum size of a key generated by `fdshare()`.
#define FDKEY_128 25  ///< The size of a buffer needed to hold a 128-bit key.
#define FDKEY_256 45  ///< The size of a buffer needed to hold a 256-bit key.
#define FDKEY_512 89  ///< The size of a buffer needed to hold a 512-bit key.

typedef uint64_t fd_t;      ///< File descriptor type.
#define FDIN ((fd_t)0)      ///< Standard input file descriptor.
#define FDOUT ((fd_t)1)     ///< Standard output file descriptor.
#define FDERR ((fd_t)2)     ///< Standard error file descriptor.
#define FDCWD ((fd_t)3)     ///< Standard current working directory file descriptor.
#define FDROOT ((fd_t)4)    ///< Standard root file descriptor.
#define FDNONE ((fd_t) - 1) ///< No file descriptor.

/**
 * @brief System call for sharing a file descriptor with another process.
 *
 * @param fd The file descriptor to share.
 * @param key Output buffer to store the generated key.
 * @param size The size of the output buffer.
 * @param timeout The time until the shared file descriptor expires. If `CLOCKS_NEVER`, it never expires.
 * @return An appropriate status value.
 */
static inline status_t fdshare(fd_t fd, char* key, size_t size, clock_t timeout)
{
    return syscall4(SYS_FD_SHARE, NULL, fd, (uintptr_t)key, size, timeout);
}

/**
 * @brief System call for claiming a shared file descriptor.
 *
 * After claiming a shared file descriptor, the key is no longer valid and cannot be used again.
 *
 * @param out Output pointer to store the claimed file descriptor.
 * @param key The key identifying the shared file descriptor.
 * @return An appropriate status value.
 */
static inline status_t fdclaim(fd_t* out, const char* key)
{
    return syscall1(SYS_FD_CLAIM, out, (uintptr_t)key);
}

/**
 * @brief System call for duplicating file descriptors.
 *
 * @param oldFd The open file descriptor to duplicate.
 * @param newFd Output pointer for the new file descriptor, if `FDNONE` any free file descriptor will be used,
 * otherwise the specified file descriptor will be used.
 * @return An appropriate status value.
 */
static inline status_t fddup(fd_t oldFd, fd_t* newFd)
{
    return syscall2(SYS_FD_DUP, newFd, oldFd, *newFd);
}

typedef uint64_t fsvol_t; ///< Filesystem volume id type.

/**
 * @brief System call for binding a source path to a target path.
 *
 * @param target The file descriptor to the target location where the source will appear.
 * @param source The file descriptor to the source location.
 * @return An appropriate status value.
 */
static inline status_t fsbind(fd_t target, fd_t source)
{
    return syscall2(SYS_FS_BIND, NULL, target, source);
}

/**
 * @brief System call for unbinding a path.
 *
 * @param target The file descriptor to the target location to unbind.
 * @return An appropriate status value.
 */
static inline status_t fsunbind(fd_t target)
{
    return syscall1(SYS_FS_UNBIND, NULL, target);
}

typedef uint64_t vnum_t; ///< Virtual node number type.

typedef uint16_t vtype_t;  ///< Virtual node type enum.
#define VTYPE_UNKNOWN 0    ///< Unknown file type.
#define VTYPE_REGULAR 1    ///< Regular file.
#define VTYPE_DIRECTORY 3  ///< Directory.
#define VTYPE_SYMLINK 4    ///< Symbolic link.
#define VTYPE_DEVICE 5     ///< Device file.
#define VTYPE_SYSTEM 6     ///< System file, used for exposing kernel information to user space.

typedef uint16_t vattr_t; ///< Virtual node attribute operations.
#define _VATTR_GET(x) (((x) << 1) & ~1)
#define _VATTR_SET(x) (((x) << 1) | 1)
#define VATTR_GET_SIZE _VATTR_GET(0)       ///< Get the size of the file.
#define VATTR_SET_SIZE _VATTR_SET(0)       ///< Set the size of the file.
#define VATTR_GET_BLOCKS _VATTR_GET(1)     ///< Get the number of blocks allocated.
#define VATTR_GET_BLOCK_SIZE _VATTR_GET(2) ///< Get the block size.
#define VATTR_GET_MAX_SIZE _VATTR_GET(3)   ///< Get the maximum file size.
#define VATTR_GET_ATIME _VATTR_GET(4)      ///< Get the access time.
#define VATTR_SET_ATIME _VATTR_SET(4)      ///< Set the access time.
#define VATTR_GET_MTIME _VATTR_GET(5)      ///< Get the modification time.
#define VATTR_SET_MTIME _VATTR_SET(5)      ///< Set the modification time.
#define VATTR_GET_CTIME _VATTR_GET(6)      ///< Get the change time.
#define VATTR_SET_CTIME _VATTR_SET(6)      ///< Set the change time.
#define VATTR_GET_BTIME _VATTR_GET(7)      ///< Get the birth time.
#define VATTR_SET_BTIME _VATTR_SET(7)      ///< Set the birth time.
#define VATTR_GET_NUM _VATTR_GET(8)        ///< Get the file number.
#define VATTR_GET_VOL _VATTR_GET(9)        ///< Get the volume ID.
#define VATTR_GET_NLINK _VATTR_GET(10)     ///< Get the number of hard links.
#define VATTR_GET_TYPE _VATTR_GET(11)      ///< Get the file type.

#define VATTR_IS_SET(attr) ((attr) & 1)
#define VATTR_IS_GET(attr) (!((attr) & 1))

typedef uint64_t vmask_t;         ///< Bitmask of which fields are valid within a `vinfo_t` structure.
#define VMASK_SIZE (1 << 0)       ///< File size is valid.
#define VMASK_BLOCKS (1 << 1)     ///< Blocks allocated is valid.
#define VMASK_BLOCK_SIZE (1 << 2) ///< Block size is valid.
#define VMASK_MAX_SIZE (1 << 3)   ///< Maximum file size is valid.
#define VMASK_ATIME (1 << 4)      ///< Access time is valid.
#define VMASK_MTIME (1 << 5)      ///< Modification time is valid.
#define VMASK_CTIME (1 << 6)      ///< Change time is valid.
#define VMASK_BTIME (1 << 7)      ///< Birth/Creation time is valid.
#define VMASK_NUM (1 << 8)        ///< File number is valid.
#define VMASK_VOL (1 << 9)        ///< Volume ID is valid.
#define VMASK_NLINK (1 << 10)     ///< Number of hard links is valid.
#define VMASK_FLAGS (1 << 11)     ///< File flags are valid.
#define VMASK_TYPE (1 << 12)      ///< File type is valid.
#define VMASK_NAME (1 << 13)      ///< File name is valid.
#define VMASK_MODE (1 << 14)      ///< File mode is valid.

/**
 * @brief Virtual node information structure.
 * @struct vinfo_t
 */
typedef struct vinfo
{
    vmask_t mask;   ///< Bitmask of which fields are valid.
    size_t size;         ///< File size in bytes.
    size_t blocks;       ///< Blocks allocated.
    size_t blockSize;    ///< Block size in bytes.
    size_t maxSize;      ///< Maximum file size.
    clock_t atime;       ///< Access time (ns).
    clock_t mtime;       ///< Modification time (ns).
    clock_t ctime;       ///< Change time (ns).
    clock_t btime;       ///< Birth/Creation time (ns).
    vnum_t num;        ///< File number, depends on the file system, for example, inode number in ext4.
    fsvol_t vol;        ///< Volume ID.
    uint32_t nlink;      ///< Number of hard links.
    vtype_t type;    ///< File type.
    char name[MAX_PATH]; ///< File name.
    char mode[MAX_NAME]; ///< File mode represented by their short-hand.
    uint8_t _reserved[123];
} vinfo_t;

#ifdef static_assert
static_assert(sizeof(vinfo_t) == 512, "vinfo_t is not 512 bytes");
#endif

/** @} */

#if defined(__cplusplus)
}
#endif

#endif
